### ISSUE TITLE
Help -> Discussion board not working

### ISSUE THREAD

**Issue by chelsea-brown** [Martini-Force-Field-Initiative/Martini-Force-Field-Initiative.github.io#24]
It goes to a 404 page not found

**Comment by chelsea-brown** [comment]
Same with Help -> Report an issue

**Comment by danielpastor97** [comment]
Thank you for reporting this @chelsea-brown , I think it is because the Discussion Board is still not visible to the public. I can see it normally but it is maybe that Luis gave me access to it at some point, I can not recall. Is this the case @Lp0lp ?

**Comment by chelsea-brown** [comment]
Since the website has gone live I have checked this again and it is still the case that the 404 error appears after clicking these links.

**Comment by Lp0lp** [comment]
Hello! I have not made it open to the public yet. I am fixing it!

**Comment by Lp0lp** [comment]
Good catch! It should be now fixed. For reference, the visibility of the discussions page is tied to the visibility of the repository it is associated with. In this case it is this [one](https://github.com/Martini-Force-Field-Initiative/MartiniDiscussions). 

At the time I wanted it separate from the website repo, because it could be of interest to hide one repo vs the other for whatever reason. This is something we can revisit and assign the discussion board to the website repo if we so wish!
